# Generated by Django 2.2.3 on 2019-07-28 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Messaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=250)),
                ('recevier', models.CharField(max_length=250)),
                ('content', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('creation_date', models.CharField(max_length=250)),
                ('readable', models.CharField(max_length=10)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chat.User')),
            ],
        ),
    ]
