# Generated by Django 2.2.3 on 2019-08-01 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_auto_20190729_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
